version: '2'
services:
  prometheus:
    image: "prom/prometheus"
    hostname: prometheus
    container_name: prometheus
    networks:
      - mynetwork
    ports:
      - '9090:9090'
    volumes:
      - /home/workspace/promethues:/etc/prometheus #prometheus 配置文件所在路径映射到容器内
    restart: always
#  node-exporter:
#    image: "prom/node-exporter"
#    hostname: node-exporter
#    container_name: node-exporter
#    ports:
#      - '9100:9100'
#    volumes:
#      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - /:/rootfs:ro
#    restart: always
#    network_mode: host
#    command:
#      - '--path.procfs=/host/proc'
#      - '--path.sysfs=/host/sys'
#      - '--path.rootfs=/rootfs'
#  grafana:
#    image: "grafana/grafana"
#    hostname: grafana
#    container_name: grafana
#    networks:
#      - mynetwork
#    ports:
#      - '3000:3000'
#    restart: always
  alertmanager:
    image: "prom/alertmanager"
    hostname: alertmanager
    container_name: alertmanager
    networks:
      - mynetwork
    ports:
      - '9093:9093'
    volumes:
      - /home/workspace/promethues:/etc/alertmanager #alertmanager 配置文件所在路径映射到容器内
    restart: always
  pushgateway:
    image: "prom/pushgateway"
    hostname: pushgateway
    container_name: pushgateway
    networks:
      - mynetwork
    ports:
      - '9091:9091'
    restart: always
networks:
  mynetwork: